before:
  hooks:
    - go mod download
builds:
  -
    id: protolint
    env:
      - CGO_ENABLED=0
    main: ./cmd/protolint/main.go
    binary: protolint
    goos:
      - windows
      - darwin
      - linux
    ldflags:
      - -s -w -X github.com/yoheimuta/protolint/internal/cmd.version={{.Version}} -X github.com/yoheimuta/protolint/internal/cmd.revision={{.ShortCommit}}
  -
    id: protoc-gen-protolint
    env:
      - CGO_ENABLED=0
    main: ./cmd/protoc-gen-protolint/main.go
    binary: protoc-gen-protolint
    goos:
      - windows
      - darwin
      - linux
    ldflags:
      - -s -w -X github.com/yoheimuta/protolint/internal/cmd/protocgenprotolint.version={{.Version}} -X github.com/yoheimuta/protolint/internal/cmd/protocgenprotolint.revision={{.ShortCommit}}
archives:
  -
    replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
brews:
  -
    name: protolint
    tap:
      owner: yoheimuta
      name: homebrew-protolint
    commit_author:
      name: goreleaserbot
      email: yoheimuta@gmail.com
    folder: Formula
    description: "Pluggable tool to enforce Protocol Buffer style and conventions"
    homepage: "https://github.com/yoheimuta/protolint"
    test: |
      system "#{bin}/protolint version"
      system "#{bin}/protoc-gen-protolint version"
    install: |
      bin.install "protolint"
      bin.install "protoc-gen-protolint"
      prefix.install "LICENSE"
