version: 2
jobs:
  lint:
    docker:
      - image: circleci/golang:1.13.4
        environment:
          GO111MODULE: "on"
    working_directory: /go/src/github.com/yoheimuta/protolint
    steps:
      - checkout
      - run: make dev/install/dep
      - run: make test/lint
  test:
    docker:
      - image: circleci/golang:1.16.5
        environment:
          GO111MODULE: "on"
    working_directory: /go/src/github.com/yoheimuta/protolint
    steps:
      - checkout
      - run: make test
  deploy:
    docker:
      - image: circleci/golang:1.16.5
        environment:
          GO111MODULE: "on"
    working_directory: /go/src/github.com/yoheimuta/protolint
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
      - run: curl -sL https://git.io/goreleaser | bash
workflows:
  version: 2
  lint_and_test:
    jobs:
      - lint
      - test
  deploy:
    jobs:
      - deploy:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v[0-9]+\.[0-9]+\.[0-9]+$/
